openapi: 3.0.0
info:
  title: Music library
  description: This is a simple API for managing songs.
  version: 1.0.0
servers:
  - url: http://localhost:{port}
    variables:
      port:
        default: "8080"

paths:
  /songs:
    get:
      summary: Get paginated songs
      parameters:
        - name: filter
          in: query
          required: false
          schema:
            type: string
        - name: page
          in: query
          required: false
          schema:
            type: integer
            example: 1
        - name: pageSize
          in: query
          required: false
          schema:
            type: integer
            example: 5
      responses:
        '200':
          description: A list of songs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Song'
        '500':
          description: Internal Server Error
  /song/add:
    post:
      summary: Add a new song
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Song'
      responses:
        '200':
          description: Song added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SongDetails'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /songs/delete:
    delete:
      summary: Delete a song
      parameters:
        - name: group
          in: query
          required: true
          schema:
            type: string
        - name: song
          in: query
          required: true
          schema:
            type: string
        - name: id
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Song deleted successfully
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /songs/update:
    put:
      summary: Update a song
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SongDetails'
      responses:
        '200':
          description: Song updated successfully
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /songs/text:
    get:
      summary: Get paginated song lyrics
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
        - name: page
          in: query
          required: true
          schema:
            type: integer
        - name: size
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A list of song lyrics
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /songs/info:
    get:
      summary: Get song information
      parameters:
        - name: group
          in: query
          required: true
          schema:
            type: string
        - name: song
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Song information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SongDetails'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

components:
  schemas:
    Song:
      type: object
      properties:
        group:
          type: string
        song:
          type: string

    SongDetails:
      type: object
      properties:
        release_date:
          type: string
        liryc:
          type: string
        link:
          type: string
