// Code generated by mockery v2.45.1. DO NOT EDIT.

package mocks

import (
	entity "EffectiveMobile_Go/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// SongRepository is an autogenerated mock type for the SongRepository type
type SongRepository struct {
	mock.Mock
}

type SongRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SongRepository) EXPECT() *SongRepository_Expecter {
	return &SongRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: song
func (_m *SongRepository) Add(song entity.Song) error {
	ret := _m.Called(song)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Song) error); ok {
		r0 = rf(song)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SongRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type SongRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - song entity.Song
func (_e *SongRepository_Expecter) Add(song interface{}) *SongRepository_Add_Call {
	return &SongRepository_Add_Call{Call: _e.mock.On("Add", song)}
}

func (_c *SongRepository_Add_Call) Run(run func(song entity.Song)) *SongRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entity.Song))
	})
	return _c
}

func (_c *SongRepository_Add_Call) Return(_a0 error) *SongRepository_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SongRepository_Add_Call) RunAndReturn(run func(entity.Song) error) *SongRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: group, song, id
func (_m *SongRepository) Delete(group string, song string, id int) error {
	ret := _m.Called(group, song, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, int) error); ok {
		r0 = rf(group, song, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SongRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type SongRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - group string
//   - song string
//   - id int
func (_e *SongRepository_Expecter) Delete(group interface{}, song interface{}, id interface{}) *SongRepository_Delete_Call {
	return &SongRepository_Delete_Call{Call: _e.mock.On("Delete", group, song, id)}
}

func (_c *SongRepository_Delete_Call) Run(run func(group string, song string, id int)) *SongRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *SongRepository_Delete_Call) Return(_a0 error) *SongRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SongRepository_Delete_Call) RunAndReturn(run func(string, string, int) error) *SongRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: filter
func (_m *SongRepository) GetAll(filter string) ([]entity.Song, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []entity.Song
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entity.Song, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(string) []entity.Song); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Song)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SongRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type SongRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - filter string
func (_e *SongRepository_Expecter) GetAll(filter interface{}) *SongRepository_GetAll_Call {
	return &SongRepository_GetAll_Call{Call: _e.mock.On("GetAll", filter)}
}

func (_c *SongRepository_GetAll_Call) Run(run func(filter string)) *SongRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *SongRepository_GetAll_Call) Return(_a0 []entity.Song, _a1 error) *SongRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SongRepository_GetAll_Call) RunAndReturn(run func(string) ([]entity.Song, error)) *SongRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllDetails provides a mock function with given fields: group, song
func (_m *SongRepository) GetAllDetails(group string, song string) (entity.SongDetails, error) {
	ret := _m.Called(group, song)

	if len(ret) == 0 {
		panic("no return value specified for GetAllDetails")
	}

	var r0 entity.SongDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (entity.SongDetails, error)); ok {
		return rf(group, song)
	}
	if rf, ok := ret.Get(0).(func(string, string) entity.SongDetails); ok {
		r0 = rf(group, song)
	} else {
		r0 = ret.Get(0).(entity.SongDetails)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(group, song)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SongRepository_GetAllDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllDetails'
type SongRepository_GetAllDetails_Call struct {
	*mock.Call
}

// GetAllDetails is a helper method to define mock.On call
//   - group string
//   - song string
func (_e *SongRepository_Expecter) GetAllDetails(group interface{}, song interface{}) *SongRepository_GetAllDetails_Call {
	return &SongRepository_GetAllDetails_Call{Call: _e.mock.On("GetAllDetails", group, song)}
}

func (_c *SongRepository_GetAllDetails_Call) Run(run func(group string, song string)) *SongRepository_GetAllDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *SongRepository_GetAllDetails_Call) Return(_a0 entity.SongDetails, _a1 error) *SongRepository_GetAllDetails_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SongRepository_GetAllDetails_Call) RunAndReturn(run func(string, string) (entity.SongDetails, error)) *SongRepository_GetAllDetails_Call {
	_c.Call.Return(run)
	return _c
}

// GetText provides a mock function with given fields: id, page, size
func (_m *SongRepository) GetText(id int, page int, size int) ([]string, error) {
	ret := _m.Called(id, page, size)

	if len(ret) == 0 {
		panic("no return value specified for GetText")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, int) ([]string, error)); ok {
		return rf(id, page, size)
	}
	if rf, ok := ret.Get(0).(func(int, int, int) []string); ok {
		r0 = rf(id, page, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, int) error); ok {
		r1 = rf(id, page, size)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SongRepository_GetText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetText'
type SongRepository_GetText_Call struct {
	*mock.Call
}

// GetText is a helper method to define mock.On call
//   - id int
//   - page int
//   - size int
func (_e *SongRepository_Expecter) GetText(id interface{}, page interface{}, size interface{}) *SongRepository_GetText_Call {
	return &SongRepository_GetText_Call{Call: _e.mock.On("GetText", id, page, size)}
}

func (_c *SongRepository_GetText_Call) Run(run func(id int, page int, size int)) *SongRepository_GetText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *SongRepository_GetText_Call) Return(_a0 []string, _a1 error) *SongRepository_GetText_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SongRepository_GetText_Call) RunAndReturn(run func(int, int, int) ([]string, error)) *SongRepository_GetText_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: song, id
func (_m *SongRepository) Update(song entity.SongDetails, id int) error {
	ret := _m.Called(song, id)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.SongDetails, int) error); ok {
		r0 = rf(song, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SongRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type SongRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - song entity.SongDetails
//   - id int
func (_e *SongRepository_Expecter) Update(song interface{}, id interface{}) *SongRepository_Update_Call {
	return &SongRepository_Update_Call{Call: _e.mock.On("Update", song, id)}
}

func (_c *SongRepository_Update_Call) Run(run func(song entity.SongDetails, id int)) *SongRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entity.SongDetails), args[1].(int))
	})
	return _c
}

func (_c *SongRepository_Update_Call) Return(_a0 error) *SongRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SongRepository_Update_Call) RunAndReturn(run func(entity.SongDetails, int) error) *SongRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewSongRepository creates a new instance of SongRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSongRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SongRepository {
	mock := &SongRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
